export type ClientDetail = {
    photo: string;
    location: string;
    compnay: string;
    project: string;
    date: Date;
    clientName: string;
    phoneNumber:number;
    gender:string;
    email:string;
  };
  
  export const clientDetails: ClientDetail[] = [
    {
      photo:
        "https://png.pngtree.com/element_our/20190531/ourmid/pngtree-customer-service-avatar-image_1288891.jpg",
      location: "chennai",
      clientName: "Mike",
      compnay: "BBQ",
      date: new Date(15/2/2024),
      project: "Employee Management System",
      gender : "Male",
      phoneNumber:9856032147,
      email:"Mike@gmail.com",

    },
    {
        photo:
          "https://png.pngtree.com/element_our/20190531/ourmid/pngtree-customer-service-avatar-image_1288891.jpg",
        location : "Nevermore",
        clientName: "Enid",
        compnay : "BBQ",
        date : new Date(15/4/2025),
        project:"Employee Management System",
        gender : "Female",
      phoneNumber:7563201489,
      email:"Enid@gmail.com",
      },
      {
        photo : 
        "https://banner2.cleanpng.com/20180612/ih/kisspng-computer-icons-avatar-user-profile-clip-art-5b1f69f0e68650.4078880515287853929442.jpg",
        location : "Hawkins",
        clientName: "Nancy",
        compnay : "KFC",
        date : new Date(15/3/2024) ,
        project:"Student Management System" ,
        gender : "Female",
      phoneNumber:6932330145,
      email:"Nancy@gmail.com",
      },
      {
        photo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
        location : "Frankfurt",
        clientName : "Max",
        compnay : "CTS",
        date : new Date(29/2/2024),
        project:"Teacher Management System",
        gender : "Female",
      phoneNumber:960000521,
      email:"max@gmail.com",
    },
      {
        photo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
        location : "Berlin",
        clientName: "Eleven", 
        compnay : "Amazon",
        date : new Date(14/12/2024),
        project:"Food Delivery App",
        gender : "Female",
      phoneNumber:8885533366,
      email:"Eleven@gmail.com",
      },
     
      {
          photo :
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
          location : "chennai",
          clientName : "Steve",
          compnay : "Ibaccoo",
          date : new Date(6/9/2024),
          project:"E-commerce Websites",
          gender : "Male",
      phoneNumber:9995478965,
      email:"Steve@gmail.com",
      },
      {
        photo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
        location : "Canada",
        clientName: "Robin", 
        compnay : "Amazon",
        date : new Date(10/5/2024) ,
        project:"Todo list" ,
        gender : "Female",
      phoneNumber:6325140987,
      email:"Robbin@gmail.com",
      },
      {
          photo:
          "https://png.pngtree.com/png-vector/20190329/ourmid/pngtree-vector-avatar-icon-png-image_889567.jpg",
          location : "Sweden",
          clientName : "Max S",
          compnay : "CTS",
          date : new Date(25/5/2024),
          project:"Employee Management System",
          gender : "Female",
      phoneNumber:9658473201,
      email:"MaxS@gmail.com",
      },
      {
        photo:
        "https://png.pngtree.com/png-vector/20190329/ourmid/pngtree-vector-avatar-icon-png-image_889567.jpg",
        location : "H-LAB",
        clientName : "Vecna",
        compnay : "Zoho",
        date : new Date(1/12/2025),
        project:"Analatics Management System",
        gender : "Female",
      phoneNumber:6549820137,
      email:"Vecna@gmail.com",
      },
    {
      photo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
      location : "Prayer Tower",
      clientName: "Eleven", 
      compnay : "Amazon",
      date : new Date(6/11/2024),
      project:"Jesus Call",
      gender : "Female",
      phoneNumber:7563201489,
      email:"JesusCall@gmail.com", 
    },
   
    {
        photo :
        "h",
        location : "Dindigul",
        clientName : "Steve",
        compnay : "Ibaccoo",
        date : new Date(1/2/2025),
        project:"Student Management System",
        gender : "Male",
      phoneNumber:9632010254,
      email:"Steve@gmail.com",
    },
    {
      photo:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6yFuS-rObxjEhYFYw3cmWa3ISqX6X4pGyUjBml8ATCORbNOd-84zvqQMqH_Y8Mu1PXUk&usqp=CAU",
      location : "Nammakal",
      clientName: "Robin S", 
      compnay : "Amazon",
      date : new Date(2/1/2025),
      project:"Bill Calculating",
      gender : "Female",
      phoneNumber:9658714526,
      email:"RobinS@gmail.com",
    },
    {
        photo:
        "https://png.pngtree.com/png-vector/20190329/ourmid/pngtree-vector-avatar-icon-png-image_889567.jpg",
        location : "chennai",
        clientName : "Max V",
        compnay : "CTS",
        date : new Date(1/11/2024),
        project:"Social Media website",
        gender : "Female",
      phoneNumber:6985470012,
      email:"Max V@gmail.com",
    },
    {
      photo:
      "https://png.pngtree.com/png-vector/20190329/ourmid/pngtree-vector-avatar-icon-png-image_889567.jpg",
      location : "chennai",
      clientName : "Hawkins",
      compnay : "Zoho",
      date : new Date(2/5/2024),
      project:"Employee Management System",
      gender : "Male",
      phoneNumber:6859471254,
      email:"Will@gmail.com",
    },
    {
      photo: "https://example.com/avatar1.jpg",
      location: "Mumbai",
      clientName: "Alice",
      compnay: "Google",
      date: new Date(2023, 6, 10),
      project: "Sales Dashboard",
      gender: "Female",
      phoneNumber: 9876543210,
      email: "alice@gmail.com",
    },
    {
      photo: "https://example.com/avatar2.jpg",
      location: "Delhi",
      clientName: "Bob",
      compnay: "Microsoft",
      date: new Date(2023, 9, 20),
      project: "Inventory Management",
      gender: "Male",
      phoneNumber: 1234567890,
      email: "bob@gmail.com",
    },
    {
      photo: "https://example.com/avatar3.jpg",
      location: "Bangalore",
      clientName: "Charlie",
      compnay: "Apple",
      date: new Date(2023, 12, 15),
      project: "Employee Management System",
      gender: "Male",
      phoneNumber: 2345678901,
      email: "charlie@gmail.com",
    },
    {
      photo: "https://example.com/avatar4.jpg",
      location: "Hyderabad",
      clientName: "Daisy",
      compnay: "Amazon",
      date: new Date(2024, 3, 5),
      project: "Social Media Analytics",
      gender: "Female",
      phoneNumber: 3456789012,
      email: "daisy@gmail.com",
    },
    {
      photo: "https://example.com/avatar5.jpg",
      location: "Chennai",
      clientName: "Eva",
      compnay: "Facebook",
      date: new Date(2024, 5, 20),
      project: "Food Delivery App",
      gender: "Female",
      phoneNumber: 4567890123,
      email: "eva@gmail.com",
    },
    {
      photo: "https://example.com/avatar6.jpg",
      location: "Pune",
      clientName: "Frank",
      compnay: "Tesla",
      date: new Date(2024, 8, 10),
      project: "E-commerce Websites",
      gender: "Male",
      phoneNumber: 5678901234,
      email: "frank@gmail.com",
    },
    {
      photo: "https://example.com/avatar7.jpg",
      location: "Kolkata",
      clientName: "Grace",
      compnay: "SpaceX",
      date: new Date(2024, 10, 15),
      project: "Todo list",
      gender: "Female",
      phoneNumber: 6789012345,
      email: "grace@gmail.com",
    },
    {
      photo: "https://example.com/avatar8.jpg",
      location: "Ahmedabad",
      clientName: "Henry",
      compnay: "Microsoft",
      date: new Date(2025, 1, 25),
      project: "Employee Management System",
      gender: "Male",
      phoneNumber: 7890123456,
      email: "henry@gmail.com",
    },
    {
      photo: "https://example.com/avatar9.jpg",
      location: "Jaipur",
      clientName: "Ivy",
      compnay: "Google",
      date: new Date(2025, 3, 10),
      project: "Analatics Management System",
      gender: "Female",
      phoneNumber: 8901234567,
      email: "ivy@gmail.com",
    },
    {
      photo: "https://example.com/avatar10.jpg",
      location: "Lucknow",
      clientName: "Jack",
      compnay: "Apple",
      date: new Date(2025, 5, 5),
      project: "Jesus Call",
      gender: "Male",
      phoneNumber: 9012345678,
      email: "jack@gmail.com",
    },
    {
      photo: "https://example.com/avatar11.jpg",
      location: "Kochi",
      clientName: "Katie",
      compnay: "Amazon",
      date: new Date(2025, 7, 15),
      project: "Student Management System",
      gender: "Female",
      phoneNumber: 1234509876,
      email: "katie@gmail.com",
    },
    {
      photo: "https://example.com/avatar12.jpg",
      location: "Goa",
      clientName: "Leo",
      compnay: "Ibaccoo",
      date: new Date(2025, 9, 20),
      project: "Bill Calculating",
      gender: "Male",
      phoneNumber: 2345098765,
      email: "leo@gmail.com",
    },
    {
      photo: "https://example.com/avatar13.jpg",
      location: "Agra",
      clientName: "Mia",
      compnay: "Zoho",
      date: new Date(2025, 11, 5),
      project: "Social Media website",
      gender: "Female",
      phoneNumber: 3450987654,
      email: "mia@gmail.com",
    },
    {
      photo: "https://example.com/avatar14.jpg",
      location: "Shimla",
      clientName: "Nate",
      compnay: "CTS",
      date: new Date(2026, 1, 10),
      project: "Employee Management System",
      gender: "Male",
      phoneNumber: 4567896543,
      email: "nate@gmail.com",
    },
    {
      photo: "https://example.com/avatar15.jpg",
      location: "Nagpur",
      clientName: "Olivia",
      compnay: "Amazon",
      date: new Date(2026, 3, 20),
      project: "Sales Dashboard",
      gender: "Female",
      phoneNumber: 5678965432,
      email: "olivia@gmail.com",
    },
    {
      photo: "https://example.com/avatar16.jpg",
      location: "Varanasi",
      clientName: "Peter",
      compnay: "Google",
      date: new Date(2026, 5, 15),
      project: "Inventory Management",
      gender: "Male",
      phoneNumber: 6789654321,
      email: "peter@gmail.com",
    },
    {
      photo: "https://example.com/avatar17.jpg",
      location: "Patna",
      clientName: "Queenie",
      compnay: "Apple",
      date: new Date(2026, 7, 10),
      project: "Employee Management System",
      gender: "Female",
      phoneNumber: 7896543210,
      email: "queenie@gmail.com",
    },
    {
      photo: "https://example.com/avatar18.jpg",
      location: "Ranchi",
      clientName: "Ryan",
      compnay: "Facebook",
      date: new Date(2026, 9, 5),
      project: "Social Media Analytics",
      gender: "Male",
      phoneNumber: 8965432109,
      email: "ryan@gmail.com",
    },
    {
      photo: "https://example.com/avatar20.jpg",
      location: "Chandigarh",
      clientName: "Tom",
      compnay: "Microsoft",
      date: new Date(2027, 1, 1),
      project: "Sales Dashboard",
      gender: "Male",
      phoneNumber: 9876543210,
      email: "tom@gmail.com",
    },
    {
      photo: "https://example.com/avatar21.jpg",
      location: "Guwahati",
      clientName: "Uma",
      compnay: "Google",
      date: new Date(2027, 3, 1),
      project: "Inventory Management",
      gender: "Female",
      phoneNumber: 1234567890,
      email: "uma@gmail.com",
    },
    {
      photo: "https://example.com/avatar22.jpg",
      location: "Indore",
      clientName: "Victor",
      compnay: "Apple",
      date: new Date(2027, 5, 1),
      project: "Employee Management System",
      gender: "Male",
      phoneNumber: 2345678901,
      email: "victor@gmail.com",
    },
    {
      photo: "https://example.com/avatar23.jpg",
      location: "Jaipur",
      clientName: "Wendy",
      compnay: "Amazon",
      date: new Date(2027, 7, 1),
      project: "Social Media Analytics",
      gender: "Female",
      phoneNumber: 3456789012,
      email: "wendy@gmail.com",
    },
    {
      photo: "https://example.com/avatar24.jpg",
      location: "Kochi",
      clientName: "Xavier",
      compnay: "Facebook",
      date: new Date(2027, 9, 1),
      project: "Food Delivery App",
      gender: "Male",
      phoneNumber: 4567890123,
      email: "xavier@gmail.com",
    },
    {
      photo: "https://example.com/avatar25.jpg",
      location: "Lucknow",
      clientName: "Yvonne",
      compnay: "Tesla",
      date: new Date(2027, 11, 1),
      project: "E-commerce Websites",
      gender: "Female",
      phoneNumber: 5678901234,
      email: "yvonne@gmail.com",
    },
    {
      photo: "https://example.com/avatar26.jpg",
      location: "Mysore",
      clientName: "Zane",
      compnay: "SpaceX",
      date: new Date(2028, 1, 1),
      project: "Todo list",
      gender: "Male",
      phoneNumber: 6789012345,
      email: "zane@gmail.com",
    },
    {
      photo: "https://example.com/avatar27.jpg",
      location: "Nagpur",
      clientName: "Amy",
      compnay: "Microsoft",
      date: new Date(2028, 3, 1),
      project: "Employee Management System",
      gender: "Female",
      phoneNumber: 7890123456,
      email: "amy@gmail.com",
    },
    {
      photo: "https://example.com/avatar28.jpg",
      location: "Ooty",
      clientName: "Ben",
      compnay: "Google",
      date: new Date(2028, 5, 1),
      project: "Analatics Management System",
      gender: "Male",
      phoneNumber: 8901234567,
      email: "ben@gmail.com",
    },
    {
      photo: "https://example.com/avatar29.jpg",
      location: "Patna",
      clientName: "Cindy",
      compnay: "Apple",
      date: new Date(2028, 7, 1),
      project: "Jesus Call",
      gender: "Female",
      phoneNumber: 9012345678,
      email: "cindy@gmail.com",
    },
    {
      photo: "https://example.com/avatar30.jpg",
      location: "Quebec",
      clientName: "David",
      compnay: "Amazon",
      date: new Date(2028, 9, 1),
      project: "Bill Calculating",
      gender: "Male",
      phoneNumber: 1234509876,
      email: "david@gmail.com",
    },
    {
      photo: "https://example.com/avatar31.jpg",
      location: "Rome",
      clientName: "Ella",
      compnay: "Zoho",
      date: new Date(2028, 11, 1),
      project: "Social Media website",
      gender: "Female",
      phoneNumber: 2345098765,
      email: "ella@gmail.com",
    },
    {
      photo: "https://example.com/avatar32.jpg",
      location: "Sydney",
      clientName: "Finn",
      compnay: "CTS",
      date: new Date(2029, 1, 1),
      project: "Employee Management System",
      gender: "Male",
      phoneNumber: 3450987654,
      email: "finn@gmail.com",
    },
    {
      photo: "https://example.com/avatar33.jpg",
      location: "Tokyo",
      clientName: "Gina",
      compnay: "Amazon",
      date: new Date(2029, 3, 1),
      project: "Sales Dashboard",
      gender: "Female",
      phoneNumber: 4567896543,
      email: "gina@gmail.com",
    },
    {
      photo: "https://example.com/avatar34.jpg",
      location: "Utrecht",
      clientName: "Hank",
      compnay: "Google",
      date: new Date(2029, 5, 1),
      project: "Inventory Management",
      gender: "Male",
      phoneNumber: 5678965432,
      email: "hank@gmail.com",
    },
    {
      photo: "https://example.com/avatar35.jpg",
      location: "Vancouver",
      clientName: "Iris",
      compnay: "Apple",
      date: new Date(2029, 7, 1),
      project: "Employee Management System",
      gender: "Female",
      phoneNumber: 6789654321,
      email: "iris@gmail.com",
    },
    {
      photo: "https://example.com/avatar36.jpg",
      location: "Wellington",
      clientName: "Jake",
      compnay: "Facebook",
      date: new Date(2029, 9, 1),
      project: "Social Media Analytics",
      gender: "Male",
      phoneNumber: 7896543210,
      email: "jake@gmail.com",
    },
    {
      photo: "https://example.com/avatar37.jpg",
      location: "Xiamen",
      clientName: "Kara",
      compnay: "Amazon",
      date: new Date(2029, 11, 1),
      project: "Food Delivery App",
      gender: "Female",
      phoneNumber: 8965432109,
      email:"kara@gmail.com"
    },
    
    ];
    